FROM node:8
MAINTAINER smisy@smisy.io

# 80 = HTTP, 443 = HTTPS, 3000 = NODESERVER server, 35729 = livereload
EXPOSE 80 443 3000 35729

# Install Utilities
RUN apt-get update -q  \
 && apt-get install -yqq \
 curl \
 git \
 ssh \
 gcc \
 make \
 build-essential \
 libkrb5-dev \
 sudo \
 apt-utils \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install NODESERVER Prerequisites
RUN npm install --quiet -g gulp yo mocha codecov nyc && npm cache verify

RUN mkdir -p /opt/node-typescript/public/lib
WORKDIR /opt/node-typescript

# Copies the local package.json file to the container
# and utilities docker container cache to not needing to rebuild
# and install node_modules/ everytime we build the docker, but only
# when the local package.json file changes.
# Install npm packages
COPY package.json /opt/node-typescript/package.json
RUN NODE_ENV=development npm install --quiet && npm cache verify

# Set development environment as default

COPY . /opt/node-typescript

# Run NODESERVER server
CMD ["npm", "test"]
